parameters:
   form.extension.uploadify.class: Ruian\UploadifyBundle\Form\Extension\UploadifyExtension

services:
    form.extension.uploadify:
        class : %form.extension.uploadify.class%
        arguments: [%ruian.uploadify.token%]
        tags:
            - { name: form.type_extension, alias: uploadify_extension }
    