parameters:
#    ruian_uploadify.example.class: Ruian\UploadifyBundle\Example

services:
    ruian.uploadify:
        class: Ruian\UploadifyBundle\Listener\RequestListener
        arguments: []
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200 }
