parameters:
#    ruian_uploadify.example.class: Ruian\UploadifyBundle\Example

services:
    ruian.uploadify:
        class: Ruian\UploadifyBundle\Listener\RequestListener
        arguments: []
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200 }

    form.type.uploadify_ressource:
        class : Ruian\UploadifyBundle\Form\RessourceType
        tags:
            - { name: form.type, alias: uploadify_ressource }