parameters:
   encrypt.uploadify.class: Ruian\UploadifyBundle\Model\Encrypt
   form.extension.uploadify.class: Ruian\UploadifyBundle\Form\Extension\Uploadify\Type\FormTypeUploadifyExtension

services:
    encrypt.uploadify:
        class : %encrypt.uploadify.class%
        arguments: [%ruian.uploadify.token%]

    form.extension.uploadify:
        class : %form.extension.uploadify.class%
        arguments: [@router, @encrypt.uploadify, %ruian.uploadify.options%]
        tags:
            - { name: form.type_extension, alias: text }
    