language: php
php:
  - 5.3
  - 5.4

before_script: 
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install
after_install:
    - cd ..
    - mv RuianUploadifyBundle UploadifyBundle